//! Wire protocol for swarm-server.
//!
//! This crate is the single source of truth for every type that crosses a
//! process boundary:
//!
//! - swarm-server ⇄ swarm-ui (Unix domain socket, local)
//! - swarm-server ⇄ iOS/iPadOS companion (HTTPS + WSS, LAN)
//!
//! The Swift client mirrors these types by hand and validates against the
//! golden fixtures generated by `cargo run --bin generate-fixtures`.
//!
//! ## Invariants
//!
//! - Every streamed frame carries `v` (protocol version) as its first field.
//! - Replay cursors are split by domain: table watermarks and per-PTY `seq`
//!   never share a `since` type.
//! - JSON is canonical for RPC; msgpack is used on WSS frames and bulk state.
//! - Unknown frame types are forward-compatible: clients must skip, not error.

#![warn(missing_debug_implementations)]

pub mod cursors;
pub mod errors;
pub mod frames;
pub mod rpc;
pub mod state;
pub mod version;

pub use cursors::{ChangeCursor, PtySeq, TableCursors};
pub use errors::{ErrorClass, ErrorPayload};
pub use frames::{Frame, FramePayload};
pub use state::{
    Annotation, Event, Instance, InstanceStatus, KvEntry, Lease, Lock, Message, PtyInfo,
    SwarmSnapshot, Task, TaskStatus, TaskType,
};
pub use version::{MIN_COMPATIBLE_VERSION, PROTOCOL_VERSION};
