import type { ThemeProfile, ThemeProfileId } from './types';

const THEME_PROFILES: ThemeProfile[] = [
  // -------------------------------------------------------------------------
  // Tron Encom OS — default theme as of rev 0.7
  //
  // White-LED hairline aesthetic on a pure-black canvas. Every chrome surface
  // gets a 1px white stroke + a multi-layer halo box-shadow. Sharp corners,
  // JetBrains Mono, uppercase HUD labels with wide letter-spacing.
  //
  // The `appearance` block is filled in so legacy CSS vars (--node-border,
  // --edge-message, badge-*) still resolve to sensible Encom-friendly values
  // for any component that hasn't been re-skinned yet. The new `chrome` block
  // carries Encom-only tokens (--led-line, --led-halo, --glow, --bg-base, etc)
  // that the Encom-scoped CSS in app.css consumes.
  //
  // The terminal palette remaps blue/cyan to white-grey neutrals per the mock
  // (decision answered 2026-04-21 — applied; reds/greens kept legible so git
  // status output stays readable).
  // -------------------------------------------------------------------------
  {
    id: 'tron-encom-os',
    name: 'Tron Encom OS',
    description: 'White-LED hairlines on pure black. Sharp corners, JetBrains Mono, uppercase HUD type. The default profile.',
    appearance: {
      defaultBackgroundOpacity: 1.0,
      canvasRgb: [0, 0, 0],
      panelRgb: [5, 7, 10],
      sidebarRgb: [5, 7, 10],
      nodeRgb: [5, 7, 10],
      nodeHeaderRgb: [0, 0, 0],
      // Hairline color — white-grey. Opacity is computed downstream so the
      // Encom theme also respects the (default 1.0) opacity slider.
      nodeBorderRgb: [216, 221, 230],
      nodeBorderSelected: '#ffffff',
      nodeBorderMobile: '#ffa94d',
      nodeTitleFg: '#f5f7fa',
      nodeStatusMuted: '#8a94a0',
      nodeStatusMutedDot: '#4a5260',
      // Status dots stay neutral except for failure (red is the one
      // non-monochrome accent the mock allows on chrome).
      statusOnline: '#ffffff',
      statusStale: '#ffa94d',
      statusOffline: '#4a5260',
      statusPending: '#c8cfd8',
      // Edges in Encom are white animated dashes. Task-state coloring maps
      // to the mock's narrow accent palette (amber/red/violet/tron) used
      // sparingly so failure/in-progress/done are still distinguishable.
      edgeTaskOpen: '#d8dde6',
      edgeTaskInProgress: '#ffa94d',
      edgeTaskDone: '#c6ff3d',
      edgeTaskFailed: '#ff3a4c',
      edgeTaskCancelled: '#4a5260',
      edgeMessage: '#ffffff',
      edgeDepBlocked: '#4a5260',
      edgeDepSatisfied: '#c6ff3d',
      // Role badges become outlined chips in Encom (see Phase 3 styles);
      // these colors only show through as text-color when scoped CSS hasn't
      // overridden them.
      badgePlanner: '#b86bff',
      badgeImplementer: '#ffffff',
      badgeReviewer: '#c6ff3d',
      badgeResearcher: '#ffa94d',
      badgeShell: '#8a94a0',
      badgeCustom: '#c8cfd8',
    },
    terminal: {
      background: '#000000',
      foreground: '#f5f7fa',
      cursor: '#ffffff',
      cursorAccent: '#000000',
      selectionBackground: '#2a3140',
      selectionForeground: '#ffffff',
      // ANSI palette — blue/cyan remapped to white-greys per mock.
      // Reds/greens/yellows kept so git diff, error highlights, and CLI
      // status output remain legible.
      black: '#2a3140',
      red: '#ff3a4c',
      green: '#c6ff3d',
      yellow: '#ffa94d',
      blue: '#c8cfd8',
      magenta: '#b86bff',
      cyan: '#d8dde6',
      white: '#f5f7fa',
      brightBlack: '#4a5260',
      brightRed: '#ff6b78',
      brightGreen: '#d8ff7a',
      brightYellow: '#ffc16b',
      brightBlue: '#ffffff',
      brightMagenta: '#d39bff',
      brightCyan: '#ffffff',
      brightWhite: '#ffffff',
    },
    chrome: {
      ledLine: '#d8dde6',
      ledLineSoft: '#6e7682',
      ledLineBright: '#ffffff',
      ledHalo:
        '0 0 0 1px rgba(255,255,255,0.08), 0 0 8px 1px rgba(255,255,255,0.35), 0 0 18px 2px rgba(255,255,255,0.18), 0 0 36px 6px rgba(255,255,255,0.08), inset 0 0 0 1px rgba(255,255,255,0.05)',
      ledHaloBright:
        '0 0 0 1px rgba(255,255,255,0.18), 0 0 12px 2px rgba(255,255,255,0.6), 0 0 28px 4px rgba(255,255,255,0.3), 0 0 56px 10px rgba(255,255,255,0.14), inset 0 0 0 1px rgba(255,255,255,0.1)',
      glow: '0 0 4px rgba(255,255,255,0.45), 0 0 12px rgba(255,255,255,0.18)',
      glowSoft: '0 0 3px rgba(255,255,255,0.30)',
      bgBase: '#000000',
      bgPanel: '#05070a',
      bgElevated: '#0b0f14',
      bgInput: '#02040a',
      fgPrimary: '#f5f7fa',
      fgSecondary: '#8a94a0',
      fgMuted: '#4a5260',
      fgDim: '#2a3140',
      accent: '#ffffff',
      accentDim: '#c8cfd8',
      accentAmber: '#ffa94d',
      accentRed: '#ff3a4c',
      accentViolet: '#b86bff',
      // Use the green sparingly for operator intent, not as the whole UI wash.
      accentTron: '#c6ff3d',
      gridColor: 'rgba(216,221,230,0.04)',
    },
  },
  {
    id: 'ghostty-dark',
    name: 'Ghostty Dark',
    description: 'The current ghostty-inspired chrome and Catppuccin-leaning terminal palette.',
    appearance: {
      defaultBackgroundOpacity: 0.68,
      canvasRgb: [17, 17, 27],
      panelRgb: [30, 30, 46],
      sidebarRgb: [30, 30, 46],
      nodeRgb: [30, 30, 46],
      nodeHeaderRgb: [24, 24, 37],
      nodeBorderRgb: [108, 112, 134],
      nodeBorderSelected: '#89b4fa',
      nodeBorderMobile: '#f9e2af',
      nodeTitleFg: '#e5e5e5',
      nodeStatusMuted: '#888888',
      nodeStatusMutedDot: '#666666',
      statusOnline: '#a6e3a1',
      statusStale: '#f9e2af',
      statusOffline: '#6c7086',
      statusPending: '#89b4fa',
      edgeTaskOpen: '#cdd6f4',
      edgeTaskInProgress: '#f9e2af',
      edgeTaskDone: '#a6e3a1',
      edgeTaskFailed: '#f38ba8',
      edgeTaskCancelled: '#6c7086',
      edgeMessage: '#89b4fa',
      edgeDepBlocked: '#6c7086',
      edgeDepSatisfied: '#a6e3a1',
      badgePlanner: '#cba6f7',
      badgeImplementer: '#89b4fa',
      badgeReviewer: '#a6e3a1',
      badgeResearcher: '#f9e2af',
      badgeShell: '#6c7086',
      badgeCustom: '#f5c2e7',
    },
    terminal: {
      background: '#1e1e1e',
      foreground: '#d4d4d4',
      cursor: '#d4d4d4',
      cursorAccent: '#1e1e1e',
      selectionBackground: '#45475a',
      selectionForeground: '#d4d4d4',
      black: '#45475a',
      red: '#f38ba8',
      green: '#a6e3a1',
      yellow: '#f9e2af',
      blue: '#89b4fa',
      magenta: '#f5c2e7',
      cyan: '#94e2d5',
      white: '#bac2de',
      brightBlack: '#585b70',
      brightRed: '#f38ba8',
      brightGreen: '#a6e3a1',
      brightYellow: '#f9e2af',
      brightBlue: '#89b4fa',
      brightMagenta: '#f5c2e7',
      brightCyan: '#94e2d5',
      brightWhite: '#a6adc8',
    },
  },
  {
    id: 'solar-dusk',
    name: 'Solar Dusk',
    description: 'Burnt copper chrome with a dusk terminal palette.',
    appearance: {
      defaultBackgroundOpacity: 0.74,
      canvasRgb: [24, 18, 16],
      panelRgb: [45, 31, 26],
      sidebarRgb: [45, 31, 26],
      nodeRgb: [52, 35, 28],
      nodeHeaderRgb: [73, 48, 37],
      nodeBorderRgb: [147, 96, 72],
      nodeBorderSelected: '#ffb067',
      nodeBorderMobile: '#f5df97',
      nodeTitleFg: '#f5ead7',
      nodeStatusMuted: '#bc9f8c',
      nodeStatusMutedDot: '#8f7567',
      statusOnline: '#8fd694',
      statusStale: '#f5c46b',
      statusOffline: '#8d7d74',
      statusPending: '#ffb067',
      edgeTaskOpen: '#f5ead7',
      edgeTaskInProgress: '#f5c46b',
      edgeTaskDone: '#8fd694',
      edgeTaskFailed: '#ee7f74',
      edgeTaskCancelled: '#8d7d74',
      edgeMessage: '#ffb067',
      edgeDepBlocked: '#8d7d74',
      edgeDepSatisfied: '#8fd694',
      badgePlanner: '#e1a4ff',
      badgeImplementer: '#ffb067',
      badgeReviewer: '#8fd694',
      badgeResearcher: '#f5c46b',
      badgeShell: '#8d7d74',
      badgeCustom: '#f6b7b4',
    },
    terminal: {
      background: '#1b1411',
      foreground: '#f3e3cf',
      cursor: '#ffb067',
      cursorAccent: '#1b1411',
      selectionBackground: '#5d4135',
      selectionForeground: '#f3e3cf',
      black: '#4d3a33',
      red: '#ee7f74',
      green: '#8fd694',
      yellow: '#f5c46b',
      blue: '#6fc2ff',
      magenta: '#e1a4ff',
      cyan: '#72d6d1',
      white: '#d4c2ae',
      brightBlack: '#8d7d74',
      brightRed: '#ff9c94',
      brightGreen: '#a9e6ad',
      brightYellow: '#ffd88f',
      brightBlue: '#90d5ff',
      brightMagenta: '#ebbaff',
      brightCyan: '#8ae5df',
      brightWhite: '#f5ead7',
    },
  },
  {
    id: 'arctic-console',
    name: 'Arctic Console',
    description: 'Cold glass chrome with a crisp ice-blue terminal palette.',
    appearance: {
      defaultBackgroundOpacity: 0.62,
      canvasRgb: [10, 17, 27],
      panelRgb: [19, 31, 45],
      sidebarRgb: [19, 31, 45],
      nodeRgb: [23, 38, 56],
      nodeHeaderRgb: [31, 50, 72],
      nodeBorderRgb: [92, 120, 148],
      nodeBorderSelected: '#79c7ff',
      nodeBorderMobile: '#9fe2ff',
      nodeTitleFg: '#e8f4ff',
      nodeStatusMuted: '#9cb6ce',
      nodeStatusMutedDot: '#6d8aa4',
      statusOnline: '#77d3a8',
      statusStale: '#ffd479',
      statusOffline: '#6d8aa4',
      statusPending: '#79c7ff',
      edgeTaskOpen: '#d6eaff',
      edgeTaskInProgress: '#ffd479',
      edgeTaskDone: '#77d3a8',
      edgeTaskFailed: '#ff8b9a',
      edgeTaskCancelled: '#6d8aa4',
      edgeMessage: '#79c7ff',
      edgeDepBlocked: '#6d8aa4',
      edgeDepSatisfied: '#77d3a8',
      badgePlanner: '#c0a3ff',
      badgeImplementer: '#79c7ff',
      badgeReviewer: '#77d3a8',
      badgeResearcher: '#ffd479',
      badgeShell: '#6d8aa4',
      badgeCustom: '#f4b1ff',
    },
    terminal: {
      background: '#0f1924',
      foreground: '#d8ebff',
      cursor: '#79c7ff',
      cursorAccent: '#0f1924',
      selectionBackground: '#28435d',
      selectionForeground: '#d8ebff',
      black: '#34485d',
      red: '#ff8b9a',
      green: '#77d3a8',
      yellow: '#ffd479',
      blue: '#79c7ff',
      magenta: '#c0a3ff',
      cyan: '#7ce8ff',
      white: '#c9d9ea',
      brightBlack: '#6d8aa4',
      brightRed: '#ffacb6',
      brightGreen: '#95e3bc',
      brightYellow: '#ffe4a1',
      brightBlue: '#a1dcff',
      brightMagenta: '#d1baff',
      brightCyan: '#9cf0ff',
      brightWhite: '#eef7ff',
    },
  },
  {
    id: 'operator-amber',
    name: 'Operator Amber',
    description: 'Black-and-amber operations mode with CRT-adjacent contrast.',
    appearance: {
      defaultBackgroundOpacity: 0.82,
      canvasRgb: [9, 7, 4],
      panelRgb: [24, 18, 9],
      sidebarRgb: [24, 18, 9],
      nodeRgb: [20, 15, 8],
      nodeHeaderRgb: [38, 28, 13],
      nodeBorderRgb: [120, 85, 28],
      nodeBorderSelected: '#ffc14d',
      nodeBorderMobile: '#ffe08a',
      nodeTitleFg: '#ffe8b2',
      nodeStatusMuted: '#c7aa69',
      nodeStatusMutedDot: '#8e6e31',
      statusOnline: '#9fe870',
      statusStale: '#ffc14d',
      statusOffline: '#8e6e31',
      statusPending: '#ffd269',
      edgeTaskOpen: '#ffe8b2',
      edgeTaskInProgress: '#ffc14d',
      edgeTaskDone: '#9fe870',
      edgeTaskFailed: '#ff8c5a',
      edgeTaskCancelled: '#8e6e31',
      edgeMessage: '#ffd269',
      edgeDepBlocked: '#8e6e31',
      edgeDepSatisfied: '#9fe870',
      badgePlanner: '#ffb86c',
      badgeImplementer: '#ffd269',
      badgeReviewer: '#9fe870',
      badgeResearcher: '#ffe08a',
      badgeShell: '#8e6e31',
      badgeCustom: '#ff9e80',
    },
    terminal: {
      background: '#0d0a04',
      foreground: '#ffdd8f',
      cursor: '#ffc14d',
      cursorAccent: '#0d0a04',
      selectionBackground: '#5c4215',
      selectionForeground: '#ffefc0',
      black: '#4a3917',
      red: '#ff8c5a',
      green: '#9fe870',
      yellow: '#ffc14d',
      blue: '#ffd269',
      magenta: '#ffb86c',
      cyan: '#f6d58d',
      white: '#e8c980',
      brightBlack: '#8e6e31',
      brightRed: '#ffab84',
      brightGreen: '#b7f48e',
      brightYellow: '#ffd983',
      brightBlue: '#ffe19e',
      brightMagenta: '#ffc995',
      brightCyan: '#ffe4a9',
      brightWhite: '#fff0c9',
    },
  },
];

export const themeProfiles = THEME_PROFILES;

export const themeProfileMap = new Map<ThemeProfileId, ThemeProfile>(
  themeProfiles.map((profile) => [profile.id, profile]),
);

export function getThemeProfile(id: ThemeProfileId | null | undefined): ThemeProfile {
  if (!id) {
    return themeProfiles[0];
  }
  return themeProfileMap.get(id) ?? themeProfiles[0];
}
